repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.13.0
  hooks:
  - id: markdownlint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-merge-conflict
  - id: destroyed-symlinks
